default: &default
  adapter: postgresql
  encoding: unicode
  host: db
  username: postgres
  password:
  pool: 5

development:
  <<: *default
  database: practice-journal_development

test:
  <<: *default
  database: practice-journal_test

production:
  <<: *default
  database: practice-journal
